__new_key_policy__: pass

__default__:
  - ../default/experiments/common.yml
  - ../default/data/dupre.yml
  - ../default/data/stitching.yml

__run__:
  __main__: src.experiments.optical_flow:main
  __name__: "{flow}{specs}-{scale}-{blur}/{alpha}-{delta}/{seed}"
  __output_dir__: experiment_folder/optical_flow/  # Main output directoy. True output_dir is output_dir/__name__

run_dupre: False  # Compute flow metrics on dupre's data
run_stitching: False  # Compute stitching metrics (not done any longer)
run_simulation: True  # Compute flow metrics on sinetra

alpha: 0.2
delta: 50.0
of_simulation: $EXPYRUN_CWD/dataset/hydra_flow/{alpha}-{delta}/{seed}/
springs_simulation: $EXPYRUN_CWD/dataset/springs_2d/{alpha}-{delta}/{seed}/

flow: farneback
specs: ""  # Additional specs to add to the name (but unused in the code)
scale: 4
blur: 1.0
