__new_key_policy__: pass

__default__:
  - ../default/experiments/common.yml
  - ../default/data/dupre.yml  # Unused, but for compatibility with the code
  - ../default/data/stitching.yml  # Same

__run__:
  __main__: src.experiments.snr_of:main
  __name__: "{flow}{specs}-{scale}-{blur}/{psnr}-{delta}/{seed}"
  __output_dir__: $EXPERIMENT_DIR/optical_flow_snr/  # Main output directoy. True output_dir is output_dir/__name__


psnr: 1.5
delta: 50.0
of_simulation_name: flow_20140829_1/1000/{psnr}-{delta}/{seed}/exp.0/
springs_simulation_name: springs/1000/{psnr}-{delta}/{seed}/exp.0/
of_simulation: $DATA_FOLDER/pasteur/simulation/{of_simulation_name}
springs_simulation: $DATA_FOLDER/pasteur/simulation/{springs_simulation_name}

flow: farneback
specs: ""  # Additional specs to add to the name (but unused in the code)
scale: 4
blur: 1.0
