__default__:
  - ./sinetra.yml

__run__:
  __name__: "dupre/{seed}"

data:
  data_type: dupre

koft:  # In this case, parameter estimation is not robust to the annotations errors... Should we keep this?
  process_std: 1.0
  flow_std: 0.5
