__new_key_policy__: pass

__default__:
  - ./simulator.yml

__run__:
  __main__: src.experiments.snr_track:main
  __output_dir__: experiment_folder/tracking_snr/  # Main output directoy. True output_dir is output_dir/__name__

tracking_method: koft

detection:
  detector: fake  # Run Fake@80% by default
  fake:
    fpr: 0.2
    fnr: 0.2
