__default__:
  - ./sinetra.yml

__run__:
  __output_dir__: experiment_folder/tracking_snr/  # Main output directoy. True output_dir is output_dir/__name__

tracking_methods: 
  - koft

detection:
  detector: fake  # Run Fake@80% by default
  fake:
    fpr: 0.2
    fnr: 0.2
